package task_engine

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/inkbloom/server/internal/dto"
	"github.com/inkbloom/server/internal/model"
	"github.com/inkbloom/server/internal/repository"
	"go.uber.org/zap"
)

// ImageTaskHandler processes image generation tasks by calling the Python AI service.
type ImageTaskHandler struct {
	aiServiceURL string
	assetRepo    repository.AssetRepository
	recordRepo   repository.AIGCRecordRepository // AIGC history (task #64)
	logger       *zap.Logger
	httpClient   *http.Client
}

// NewImageTaskHandler creates a new ImageTaskHandler.
func NewImageTaskHandler(aiServiceURL string, assetRepo repository.AssetRepository, recordRepo repository.AIGCRecordRepository, logger *zap.Logger) *ImageTaskHandler {
	return &ImageTaskHandler{
		aiServiceURL: aiServiceURL,
		assetRepo:    assetRepo,
		recordRepo:   recordRepo,
		logger:       logger,
		httpClient: &http.Client{
			Timeout: 180 * time.Second,
		},
	}
}

// Type returns the unique task type identifier.
func (h *ImageTaskHandler) Type() string { return "image_gen" }

// MaxRetries returns the maximum number of retries for image generation.
func (h *ImageTaskHandler) MaxRetries() int { return 3 }

// Execute processes an image generation task.
func (h *ImageTaskHandler) Execute(ctx context.Context, task model.Task) (json.RawMessage, error) {
	// 1. Parse the task payload
	var payload dto.AIGCGeneratePayload
	if err := json.Unmarshal(task.Payload, &payload); err != nil {
		return nil, fmt.Errorf("unmarshal payload: %w", err)
	}

	h.logger.Info("executing image generation",
		zap.String("task_id", task.ID),
		zap.String("prompt", payload.Prompt),
		zap.String("provider", payload.Provider),
	)

	// 2. Build the request to the Python AI service (scope routes the
	// output directory, task #64)
	reqBody, err := json.Marshal(map[string]interface{}{
		"prompt":   payload.Prompt,
		"width":    payload.Width,
		"height":   payload.Height,
		"provider": payload.Provider,
		"novel_id": payload.NovelID,
		"scope":    scopeOf(payload.Scope),
	})
	if err != nil {
		return nil, fmt.Errorf("marshal request: %w", err)
	}

	url := h.aiServiceURL + "/api/aigc/generate"
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(reqBody))
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	// 3. Call the Python AI service
	resp, err := h.httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("call ai service: %w", err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("ai service returned %d: %s", resp.StatusCode, string(body))
	}

	// 4. Parse the result
	var result dto.AIGCGenerateResult
	if err := json.Unmarshal(body, &result); err != nil {
		return nil, fmt.Errorf("unmarshal result: %w", err)
	}

	// Check for error in response
	if errMsg, ok := checkErrorField(body); ok {
		return nil, fmt.Errorf("ai service error: %s", errMsg)
	}

	// 5. Create the asset record in the database
	var novelID *int64
	if payload.NovelID > 0 {
		novelID = &payload.NovelID
	}

	asset := &model.Asset{
		UserID:  task.UserID,
		NovelID: novelID,
		TaskID:  task.ID,
		// Store the relative /assets/files/... URL, not the ai-service
		// machine path (task #57 fix).
		FilePath:      result.URL,
		ThumbnailPath: result.ThumbnailPath,
		Prompt:        payload.Prompt,
		Provider:      result.Provider,
		Width:         result.Width,
		Height:        result.Height,
		FileSize:      result.FileSize,
		Scope:         scopeOf(payload.Scope),
		Source:        model.AssetSourceAI,
	}

	// Every generation writes one AIGC history record (task #64).
	record := &model.AIGCRecord{
		UserID:   task.UserID,
		TaskID:   task.ID,
		Prompt:   payload.Prompt,
		Provider: result.Provider,
		NovelID:  novelID,
		Scope:    scopeOf(payload.Scope),
		Width:    result.Width,
		Height:   result.Height,
	}

	// Also set chapter_id if present in the original task
	if task.ChapterID != nil {
		asset.ChapterID = task.ChapterID
	}

	// Content-hash the generated bytes (the file is already on this
	// machine's disk) and dedupe against the user's existing gallery
	// records (task #57).
	if hash, herr := hashFileOnDisk(result.FilePath); herr == nil && hash != "" {
		asset.ContentHash = hash
		asset.DisplayName = time.Now().Format("20060102_150405") + fileExtOf(result.FilePath)
		if task.UserID > 0 {
			if existing, ferr := h.assetRepo.FindByUserHash(ctx, task.UserID, hash); ferr == nil && existing != nil {
				// Same bytes already stored for this user: drop the fresh
				// file and reuse the existing record/URL.
				_ = os.Remove(result.FilePath)
				result.URL = existing.FilePath
				result.ThumbnailPath = existing.ThumbnailPath
				h.logger.Info("generated image deduplicated against existing asset",
					zap.String("task_id", task.ID),
					zap.Int64("existing_asset_id", existing.ID),
				)
				// Every generation still produces a history record
				// pointing at the reused asset (task #64). Failure only
				// warns — the generation itself succeeded.
				h.writeRecord(ctx, task.ID, record, existing.ID)
				resultJSON, err := json.Marshal(result)
				if err != nil {
					return nil, fmt.Errorf("marshal result: %w", err)
				}
				return resultJSON, nil
			}
		}
	} else if herr != nil {
		h.logger.Warn("failed to hash generated image", zap.String("path", result.FilePath), zap.Error(herr))
	}

	if err := h.assetRepo.CreateWithRecord(ctx, asset, record); err != nil {
		// Race hardening (task #62): a concurrent generation with the same
		// content may have won the unique-index insert after our
		// FindByUserHash probe. Re-check: on hit, drop our uniquely-named
		// fresh file (never the winner's archive path) and silently reuse
		// the winning record/URL.
		if asset.ContentHash != "" && task.UserID > 0 {
			if existing, ferr := h.assetRepo.FindByUserHash(ctx, task.UserID, asset.ContentHash); ferr == nil && existing != nil {
				_ = os.Remove(result.FilePath)
				result.URL = existing.FilePath
				result.ThumbnailPath = existing.ThumbnailPath
				h.logger.Info("generated image deduplicated after insert conflict",
					zap.String("task_id", task.ID),
					zap.Int64("existing_asset_id", existing.ID),
				)
				// Dedupe hit still produces a history record (task #64).
				h.writeRecord(ctx, task.ID, record, existing.ID)
			} else {
				h.logger.Warn("failed to create asset+aigc record", zap.Error(err))
			}
		} else {
			h.logger.Warn("failed to create asset+aigc record", zap.Error(err))
		}
		// Don't fail the task if DB insert fails — image was still generated
	}

	// 6. Return the result as JSON
	resultJSON, err := json.Marshal(result)
	if err != nil {
		return nil, fmt.Errorf("marshal result: %w", err)
	}

	h.logger.Info("image generation completed",
		zap.String("task_id", task.ID),
		zap.String("url", result.URL),
	)

	return resultJSON, nil
}

// scopeOf normalizes the generation scope; legacy payloads default to novel.
func scopeOf(scope string) string {
	switch scope {
	case model.AssetScopeMedia, model.AssetScopeMemo:
		return scope
	default:
		return model.AssetScopeNovel
	}
}

// writeRecord persists an AIGC history record for dedupe paths where the
// asset row already exists (task #64). Failures only warn: the generation
// itself already succeeded.
func (h *ImageTaskHandler) writeRecord(ctx context.Context, taskID string, record *model.AIGCRecord, assetID int64) {
	if h.recordRepo == nil {
		return
	}
	rec := *record
	rec.AssetID = assetID
	if err := h.recordRepo.Create(ctx, &rec); err != nil {
		h.logger.Warn("failed to write aigc record for deduplicated generation",
			zap.String("task_id", taskID),
			zap.Int64("asset_id", assetID),
			zap.Error(err),
		)
	}
}

// checkErrorField checks if the JSON body contains an "error" field.
func checkErrorField(body []byte) (string, bool) {
	var errResp struct {
		Error string `json:"error"`
	}
	if err := json.Unmarshal(body, &errResp); err == nil && errResp.Error != "" {
		return errResp.Error, true
	}
	return "", false
}

// hashFileOnDisk streams the file through sha256 in a single pass.
func hashFileOnDisk(path string) (string, error) {
	if path == "" {
		return "", fmt.Errorf("empty path")
	}
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()
	hasher := sha256.New()
	if _, err := io.Copy(hasher, f); err != nil {
		return "", err
	}
	return hex.EncodeToString(hasher.Sum(nil)), nil
}

// fileExtOf returns the lowercase extension of a path or URL.
func fileExtOf(path string) string {
	idx := strings.LastIndexByte(path, '.')
	if idx < 0 {
		return ""
	}
	return strings.ToLower(path[idx:])
}
